# Generated by Django 4.1.7 on 2023-03-20 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import rest_framework.generics
import rest_framework.views


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('fulname', models.CharField(blank=True, max_length=100, verbose_name='Họ và tên')),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('PROFESSIONAL', 'Cán bộ chuyên môn'), ('MODERATOR', 'Cán bộ kiểm duyệt'), ('LEADER', 'Lãnh đạo'), ('ADMIN', 'Cán bộ quản trị hệ thống')], default='PROFESSIONAL', max_length=30)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_agent', models.CharField(max_length=255)),
                ('ipAddress', models.CharField(max_length=100)),
                ('path', models.CharField(max_length=255)),
                ('response_status', models.CharField(max_length=10)),
                ('request_method', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=255, null=True)),
                ('browser', models.CharField(max_length=255, null=True)),
                ('device', models.CharField(max_length=255, null=True)),
                ('request_body', models.JSONField(default=dict)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_log', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetailView',
            fields=[
                ('useractivitylog_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.useractivitylog')),
            ],
            bases=(rest_framework.views.APIView, 'account.useractivitylog'),
        ),
        migrations.CreateModel(
            name='UserListCreateView',
            fields=[
                ('useractivitylog_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.useractivitylog')),
            ],
            bases=(rest_framework.generics.ListCreateAPIView, 'account.useractivitylog'),
        ),
    ]
