# Generated by Django 4.1.7 on 2023-03-20 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên điểm tin/cảnh báo')),
                ('city', models.CharField(max_length=255, verbose_name='Thành phố')),
                ('location', models.CharField(max_length=255, verbose_name='Xã/Phường')),
                ('receiver_range', models.CharField(max_length=255, verbose_name='Phạm vi người nhận')),
                ('ages', models.CharField(max_length=30, verbose_name='Phạm vi tuổi người nhận')),
                ('gender', models.CharField(max_length=20, verbose_name='Giới tính người nhận')),
                ('device', models.CharField(max_length=50, verbose_name='Thiết bị nhận')),
                ('is_alert', models.BooleanField(default=False, help_text='Cảnh báo: True, Điểm tin: False', verbose_name='Cảnh báo/Điểm tin')),
                ('type', models.CharField(choices=[('NEWS', 'Điểm tin ATTT'), ('ALERT', 'Cảnh báo')], default='NEWS', max_length=10, verbose_name='Loại tin')),
                ('status', models.CharField(choices=[('PENDING_APPROVE', 'Chờ kiểm duyệt'), ('PENDING_SEND', 'Chờ gửi'), ('NOT_APPROVED', 'Không được phê duyệt'), ('SENT', 'Đã gửi'), ('APPROVED', 'Đã qua kiểm duyệt')], default='PENDING_SEND', max_length=20, verbose_name='Trạng thái kiểm duyệt')),
                ('is_send', models.DateTimeField(null=True)),
                ('reason_not_approved', models.TextField()),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='NewSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_new', models.TextField()),
                ('source_link', models.TextField()),
                ('source_status', models.CharField(choices=[('PAUSE', 'pause'), ('FETCHING', 'fetching')], default='PAUSE', max_length=10, verbose_name='Trạng thái bản tin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('link', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='images', verbose_name='Ảnh bìa')),
                ('source', models.TextField()),
                ('type', models.CharField(choices=[('MAIN', 'Tin chính'), ('SUB', 'Tin phụ')], max_length=7, verbose_name='Loại tin')),
                ('parent_new', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='alertnew.alertnews')),
            ],
            options={
                'default_permissions': (),
            },
        ),
    ]
