# Generated by Django 4.1.7 on 2023-03-20 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertnew', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertnews',
            name='reason_not_approved',
            field=models.TextField(null=True),
        ),
    ]
