# Generated by Django 4.1.7 on 2023-03-21 06:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('alertnew', '0005_remove_alertnews_is_send'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertnews',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alertnews',
            name='status',
            field=models.CharField(choices=[('PENDING_APPROVE', 'Chờ kiểm duyệt'), ('PENDING_SEND', 'Chờ gửi'), ('NOT_APPROVED', 'Không được phê duyệt'), ('SENT', 'Đã gửi'), ('APPROVED', 'Đã qua kiểm duyệt')], default='PENDING_APPROVE', max_length=20, verbose_name='Trạng thái kiểm duyệt'),
        ),
    ]
